### ISSUE TITLE
Minimum inscribed sphere 

### ISSUE THREAD

**Issue by Vysakh5391** [navis-org/skeletor#16]
Hello! Thank you for this library.

Is there a way to extract the radius of the minimum/maximum inscribed spheres along the skeleton path?

Thank you!

**Comment by schlegelp** [comment]
Sort of? `skeletor.post.radii` will give you a radius for each skeleton node which should be close to the inscribed sphere with the correct parameters. Two options:
1. With `method='knn'` and `n=1` will give you the inscribed sphere but only with respect to the mesh vertices, not actual intersection with the faces
2. With `method='ray'`, `aggregate="min"` and a lot of rays (`n_rays`) you should get very close to the real thing but this might not be "mathematically correct"

**Comment by Vysakh5391** [comment]
Thank you for the quick response. Fortunately, I just need an approximate representation of the sphere radius for a cross-sectional variation analysis.
