### ISSUE TITLE
Extracting extremities in a skeleton

### ISSUE THREAD

**Issue by bheiles** [navis-org/skeletor#28]
I am trying to extract the extremities in a skeleton by looking at every node and figuring out whether they are connected to only one other node. Following a suggestion from @schlegelp , I am looking at the graph representation of the skeleton.

I am testing this approach by using the example_mesh. After skeletonization by wavefront, I do:
`G=skel.get_graph().to_undirected()
for nodes in CC:
    if len(nodes)==2:
        print(nodes)`

That returns nothing.

Upon inspecting what is in CC, I find that if I do `print(nodes)` for all nodes in CC, I get this as an output: "{'node_id', 'radius', 'y', 'x', 'parent_id', 'z'}". I was expecting the actual node ids and positions rather than just the strings but I am not an expert in networkx. Is there something wrong or is it completely normal?

**Comment by schlegelp** [comment]
Are you running this as a single line? That doesn't look like it should work. Try this with a bit more verbose output:

```Python
import networkx as nx

G = skel.get_graph()

print(f'Graph has {len(G.nodes)} nodes and {len(G.edges)} edges')

CC = list(nx.connected_components(G.to_undirected()))

for i, nodes in enumerate(CC):
    print(f'Connected component {i} has {len(nodes)} nodes')
    if len(nodes)==2:
        print(nodes)
```

**Comment by bheiles** [comment]
Yes I tried inspecting what CC contains. If I do what you suggested, here is the output:
```
Graph has 6 nodes and 5 edges
Connected component 0 has 6 nodes
```

If I just do `G.edges` I get :
 ` OutEdgeView([('node_id', 'parent_id'), ('parent_id', 'x'), ('x', 'y'), ('y', 'z'), ('z', 'radius')]) `

If I just do `G.nodes` I get :
 ` NodeView(('node_id', 'parent_id', 'x', 'y', 'z', 'radius')) `


The version of networkx I'm using is 2.8.3

**Comment by schlegelp** [comment]
Oh, I just realise that I misread your original email. I thought you were after something entirely different (sorry!).

For what you are after (getting all leaf nodes) you can just look for nodes that have a degree of 1:

```Python
import networkx as nx

G = skel.get_graph()

print(f'Graph has {len(G.nodes)} nodes and {len(G.edges)} edges')

inout = []
for node in nodes:
    if G.degree[node] == 1:
        inout.append(node)

print('In-/Outlet nodes:', inout)

```

**Comment by bheiles** [comment]
That still doesn't work, it prints : "In-/Outlet nodes: ['node_id', 'radius']"

I'm working with the example mesh now. Does it work for you?

**Comment by schlegelp** [comment]
Oh yep, I found a bug here. Will fix soon. In the meantime, this should do the trick:

```Python
swc = skel.swc 
leafs = swc[~swc.node_id.isin(swc.parent_id.values) | (swc.parent_id < 0)]
```

**Comment by bheiles** [comment]
Ah yes that works better! Any way I could also get a graph representation out of this using nx.draw()?

**Comment by bheiles** [comment]
Ok I got it to work by using the following for get_graph! Thanks a lot for your help @schlegelp 

```
import networkx as nx

## Construct G
not_root = skel.swc.parent_id >= 0
nodes = skel.swc.loc[not_root]
parents = skel.swc.set_index('node_id').loc[skel.swc.loc[not_root, 'parent_id'].values]
dists = nodes[['x', 'y', 'z']].values - parents[['x', 'y', 'z']].values
dists = np.sqrt((dists ** 2).sum(axis=1))
G = nx.DiGraph()
G.add_weighted_edges_from([(s, t, w) for s, t, w in zip(nodes.node_id.values,nodes.parent_id.values, dists)])

## Draw the graph with the edges
nx.draw(G,with_labels=True)

## The edges in the graph above should correspond to the node ids in swc
swc = skel.swc 
inout = swc[~swc.node_id.isin(swc.parent_id.values) | (swc.parent_id < 0)]
```

**Comment by schlegelp** [comment]
Thanks but I'd rather not support another backend on top of trimesh for `skeletor`.

FWIW: I'm using [navis](https://github.com/navis-org/navis) for more complex visualisations. 

Seeing that the original problem is solved, I would suggest closing this issue?

**Comment by bheiles** [comment]
Yes I just posted it in case someone wanted it. Thanks so much for your help, I will also look into navis!
