### ISSUE TITLE
Set node sparsification distance

### ISSUE THREAD

**Issue by Levishery** [navis-org/skeletor#34]
Hi, I would like to get skeletons of 3D meshes of neuron segments. 
Is it possible to set the distance between nodes to a fixed value (for example 300nm) in skeletonizing? Or any post-process should be done.

Thank you!

**Comment by schlegelp** [comment]
For that you want to use [navis](https://github.com/navis-org/navis), specifically [`resample_skeleton`](https://navis.readthedocs.io/en/latest/source/generated/navis.resample_skeleton.html#navis.resample_skeleton). 

Minimal example:

```python 
>>> import navis 
>>> import skeletor as sk 
>>> # Skeletonise your mesh
>>> m = sk.skeletonize.by_wavefront(mesh)
>>> # Turn into navis neuron object 
>>> n = navis.TreeNeuron(m)
>>> # Assuming your mesh is in nm
>>> rs = navis.resampe_skeleton(n, 300)
```

**Comment by Levishery** [comment]
Thank you very much for the reply. Have a nice day :)
