### ISSUE TITLE
How do I run the code?

### ISSUE THREAD

**Issue by xiangsijiyuriluo** [navis-org/skeletor#35]
Hello, I downloaded your code on the website, but I don't know how to run it. I still don't understand the principle. Can you explain how to run the code?

**Comment by schlegelp** [comment]
Have you tried running the example code in the [README](https://github.com/navis-org/skeletor#quickstart)? What exactly are you struggling with?

**Comment by schlegelp** [comment]
Closing as stale. Feel free to add further details and re-open.
