### ISSUE TITLE
About citations of the wave fronts method

### ISSUE THREAD

**Issue by Levishery** [navis-org/skeletor#37]
Hi,
What's the best way to cite the wave fronts method in a paper? I found that all the skeletonization methods in the document have a reference except the wavefront. 
Thanks!

**Comment by schlegelp** [comment]
Hi. There is no citation for that method - it's a home-brew. That said: there might be papers out there that I'm unaware of which describe something like it 🤷  If you need something citable you could just reference skeleton by its Zenodo DOI (see the badge in the README).

**Comment by Levishery** [comment]
I see. Thank you for your reply! :)
