### ISSUE TITLE
AttributeError: module 'skeletor' has no attribute 'example_mesh'

### ISSUE THREAD

**Issue by koenterheegde0507** [navis-org/skeletor#43]
I have been using your algorithm on my laptop and it's working fine, but now im working on a different PC and I can't get it working. I have used your `pip3 install skeletor`, but i get the error like the title says. It gives the error straight from this line: `import skeletor as sk`.
I saw an earlier issue with the same problem, but in that problem it was at least possible to run part of the code. So I also can't run `print(dir(sk))
print(sk.__version__)`

However, I think it automatically shows the available methods:
`['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'sk']`. As you can see there are no methods that I can use. I'm using python 3.7.3 and pip 24.0. I've already tried to uninstall and reinstall skeletor.

Hopefully you can help me out. Thanks

**Comment by schlegelp** [comment]
That's odd. What's the output of the `print(sk.__version__)`?

**Comment by koenterheegde0507** [comment]
I can't print that either, its also doesn't show in the available methods.

**Comment by schlegelp** [comment]
Then open a terminal and run this:
```zsh
pip3 show skeletor
```

**Comment by koenterheegde0507** [comment]
`Name: skeletor
Version: 1.2.3
Summary: Python 3 library to extract skeletons from 3D meshes
Home-page: https://github.com/navis-org/skeletor
Author: Philipp Schlegel
Author-email: pms70@cam.ac.uk
License: GNU GPL V3
Location: c:\robodk\python37\lib\site-packages
Requires: igraph, ncollpyde, networkx, numpy, pandas, scikit-learn, scipy, tqdm, trimesh
Required-by:`

**Comment by schlegelp** [comment]
That looks as expected. I'm somewhat stumped as to what the issue might be. What operating system are you on? And could you please share the whole error message?

**Comment by koenterheegde0507** [comment]
OS: Microsoft Windows 11 Pro
Traceback (most recent call last):
  File ".\extractCenterline.py", line 9, in <module>
    import skeletor as sk
  File "C:\Users\Flux Robotics\OneDrive - University of Twente\Documents\Python Scripts\preoperative_plan_v1.0\skeletor.py", line 3, in <module>
    mesh = sk.example_mesh()
AttributeError: module 'skeletor' has no attribute 'example_mesh'

**Comment by schlegelp** [comment]
That looks a bit like you may have two `skeletors`:

1. This package in `c:\robodk\python37\lib\site-packages\skeletor` 
2. A `skeletor.py` script in `C:\Users\Flux Robotics\OneDrive - University of Twente\Documents\Python Scripts\preoperative_plan_v1.0\skeletor.py` 

and your Python seems to latch onto the second when you run `import skeletor as sk`.

**Comment by koenterheegde0507** [comment]
Yes, this was the answer. Thank you so much!

**Comment by schlegelp** [comment]
Perfect.
