### ISSUE TITLE
Modify the leafs or roots

### ISSUE THREAD

**Issue by anan1504** [navis-org/skeletor#47]
Hi, thank you for sharing this its very useful! I'm using it to obtain centerlines from coronary artery segmentations.
The way the arteries are structured, I have 2 roots and other nodes are branching from them. The skeleton obtained is exactly how I want, but when I traverse along the path, some nodes which are neither the start nor the end are identified as root or leaf.
Is there a way to ensure these type of nodes are connected to 2 other nodes?
I understand this is more of a graph question rather than a skeleton question.
I have added a figure for your reference. The nodes mentioned are circled in green.
![image](https://github.com/navis-org/skeletor/assets/26880063/bf1d07c8-9012-4020-8ceb-e814d97d4771)

**Comment by schlegelp** [comment]
Hi! Yeah, root nodes for the skeleton are pretty much picked at random. If I remember correctly, the wavefront method would let you pick specific seed points but even then it's not guaranteed these will end up as roots.

> Is there a way to ensure these type of nodes are connected to 2 other nodes?

I think I'm being a bit thick here. Can you explain again please?

**Comment by anan1504** [comment]
Thanks for the quick response!

Sorry I wasn't very descriptive earlier. The points marked with the green circle are not the root or the endpoints.  However they are identified as such. These are points in the middle of the skeleton. 
Is there any way to rectify this?

**Comment by schlegelp** [comment]
I see! So basically you want to re-root the skeleton to a different node (e.g. one of the leafs)?

**Comment by anan1504** [comment]
I wanted to rectify the incorrect leaf nodes. I ended up converting the graph to an undirected graph. And iterated through all the nodes and their neighbors to get the correct endpoints!
